### ISSUE TITLE
I have issue when starting the command

### ISSUE THREAD

**Issue by Baredissuck** [redc86/slash#12]
when i click the gmail of my alt gmail, the command say 

[14:21:40] Slash starting...
[14:21:40] Mail adress [rikizstore@gmail.com] succesfully setted.
[LEAK-CHECK]
     Leaks : 1 | Passwords : 2

     [1] Leak : Stealer Logs    Leak Date :

[14:21:40] Searching rikizstore@gmail.com on Pastebin...
[14:21:40] Searching rikizstore@gmail.com on Github Commits...
[14:21:40] Github commit search finished! 0 results found for rikizstore@gmail.com.
Exception in thread Thread-2 (search):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\USER\slash\api\pastebin.py", line 27, in search
    cnt = db["count"]
          ~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str

**Comment by ist9** [comment]
same here!

**Comment by iescly** [comment]
im triying to solve this but still cant solve this shit error  can anyone help me with it

**Comment by trxshlxrd** [comment]
Same issue, please update

**Comment by lKak0l** [comment]
el mismo problema bro

**Comment by iescly** [comment]
I've solved this problem check on repo

**Comment by Shazgul** [comment]
Same issue here, any fixes already out there?

**Comment by Shazgul** [comment]
```
Exception in thread Thread-2 (search):
Traceback (most recent call last):
  File "C:\Users\user2313\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\user2313\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\OSINT\slash\api\pastebin.py", line 27, in search
    cnt = db["count"]
          ~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```
